package com.urlshortener.concurrency;

import com.urlshortener.dto.CreateUrlRequest;
import com.urlshortener.dto.CreateUrlResponse;
import com.urlshortener.service.UrlService;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.kafka.test.context.EmbeddedKafka;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.concurrent.*;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Proves that base62(DB-IDENTITY-sequence) is collision-free under real concurrent load.
 * Each thread gets a unique DB-generated ID; two different IDs always produce two different
 * base62 codes, so no application-level locking is needed for short-code generation.
 *
 * Skipped automatically when Docker is not available (CI without Docker daemon).
 */
@SpringBootTest
@EmbeddedKafka(
        partitions = 1,
        topics = {"url.click.events"},
        bootstrapServersProperty = "spring.kafka.bootstrap-servers"
)
@Testcontainers(disabledWithoutDocker = true)
class ConcurrencyIntegrationTest {

    @Container
    static final PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:16-alpine");

    @Container
    @SuppressWarnings("resource")
    static final GenericContainer<?> redis = new GenericContainer<>("redis:7-alpine")
            .withExposedPorts(6379);

    @DynamicPropertySource
    static void props(DynamicPropertyRegistry r) {
        r.add("spring.datasource.url",      postgres::getJdbcUrl);
        r.add("spring.datasource.username", postgres::getUsername);
        r.add("spring.datasource.password", postgres::getPassword);
        r.add("spring.data.redis.host",     redis::getHost);
        r.add("spring.data.redis.port",     () -> redis.getMappedPort(6379));
    }

    @Autowired private UrlService urlService;

    @Test
    void parallelAutoGeneratedUrls_noShortCodeCollisions() throws Exception {
        int n = 50;
        ExecutorService pool = Executors.newFixedThreadPool(n);
        CountDownLatch startLatch = new CountDownLatch(1);
        Set<String> shortCodes = ConcurrentHashMap.newKeySet();
        List<Future<String>> futures = new ArrayList<>();

        for (int i = 0; i < n; i++) {
            final int idx = i;
            futures.add(pool.submit(() -> {
                startLatch.await(); // all threads wait until released simultaneously
                CreateUrlResponse resp = urlService.createUrl(
                        new CreateUrlRequest("https://example-" + idx + ".com", null, null), null);
                shortCodes.add(resp.shortCode());
                return resp.shortCode();
            }));
        }

        startLatch.countDown(); // release all threads at once
        for (Future<String> f : futures) f.get(30, TimeUnit.SECONDS);
        pool.shutdown();

        assertThat(shortCodes)
                .as("each of the %d concurrent creates must produce a unique short code", n)
                .hasSize(n);
    }
}
